# Generated by Django 5.2.3 on 2025-07-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeeeducation_employeeexperience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeeducation',
            name='percentagescc',
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='percentagessc',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
